In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("act_labeling_data_ohencoding.csv",encoding="cp949")

In [3]:
data.head()

,CUSTNO,GNO,CBSCORE,CBSCOREGRD,CREDITOTAMT,YSALEAMT,ESTMM,ASSETAMT,IMSAAMT,IMJUAMT,...,KIND_JOB_K,KIND_JOB_L,KIND_JOB_M,KIND_JOB_N,KIND_JOB_O,KIND_JOB_P,KIND_JOB_Q,KIND_JOB_R,KIND_JOB_S,KIND_JOB_T
0,475821,l180202101898,945,1,20,2038,37,10,10,0,...,0,0,0,0,0,0,0,0,0,0
1,74417,l230201700120,894,2,19,1175,9,25,0,25,...,0,0,0,0,0,0,0,0,0,0
2,387787,l110201603233,906,1,0,763,185,10,10,0,...,0,0,0,0,0,0,0,0,0,0
3,395418,l230201700254,881,2,14,724,11,10,10,0,...,0,0,0,0,0,0,0,0,0,0
4,190372,l200201601418,725,6,7,335,167,80,2,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
data.columns

Index(['CUSTNO', 'GNO', 'CBSCORE', 'CBSCOREGRD', 'CREDITOTAMT', 'YSALEAMT',
       'ESTMM', 'ASSETAMT', 'IMSAAMT', 'IMJUAMT', 'BUSAAMT', 'BUJUAMT',
       'BU1TOTAMT', 'GAMT', 'BIZNML_x', 'LABORCNT', 'ACTCD', 'KOSPI', '환율',
       'GDP', '소상공인체감지수', '실업률', '물가지수', '국고채', '금리', '유가등락률', '소비자심리지수',
       'KIND_JOB', 'KIND_JOB_A', 'KIND_JOB_B', 'KIND_JOB_C', 'KIND_JOB_D',
       'KIND_JOB_E', 'KIND_JOB_F', 'KIND_JOB_G', 'KIND_JOB_H', 'KIND_JOB_I',
       'KIND_JOB_J', 'KIND_JOB_K', 'KIND_JOB_L', 'KIND_JOB_M', 'KIND_JOB_N',
       'KIND_JOB_O', 'KIND_JOB_P', 'KIND_JOB_Q', 'KIND_JOB_R', 'KIND_JOB_S',
       'KIND_JOB_T'],
      dtype='object')

In [14]:
features = data[['CBSCORE', 'CBSCOREGRD', 'CREDITOTAMT', 'YSALEAMT',
       'ESTMM', 'ASSETAMT', 'IMSAAMT', 'IMJUAMT', 'BUSAAMT', 'BUJUAMT',
       'BU1TOTAMT', 'GAMT',  'LABORCNT', 'KOSPI', '환율',
       'GDP', '소상공인체감지수', '실업률', '물가지수', '국고채', '금리', '유가등락률', '소비자심리지수',
       'KIND_JOB_A', 'KIND_JOB_B', 'KIND_JOB_C', 'KIND_JOB_D',
       'KIND_JOB_E', 'KIND_JOB_F', 'KIND_JOB_G', 'KIND_JOB_H', 'KIND_JOB_I',
       'KIND_JOB_J', 'KIND_JOB_K', 'KIND_JOB_L', 'KIND_JOB_M', 'KIND_JOB_N',
       'KIND_JOB_O', 'KIND_JOB_P', 'KIND_JOB_Q', 'KIND_JOB_R', 'KIND_JOB_S',
       'KIND_JOB_T']]

act = data['ACTCD']

# 정규화 종류별 전처리

## 정규화 종류 
 - StandardScaler

In [19]:
from sklearn.preprocessing import StandardScaler
import numpy as np
scaler =StandardScaler()
scaler = scaler.fit(features)

['scaler.save']

In [7]:
data[['CBSCORE', 'CBSCOREGRD', 'CREDITOTAMT', 'YSALEAMT',
       'ESTMM', 'ASSETAMT', 'IMSAAMT', 'IMJUAMT', 'BUSAAMT', 'BUJUAMT',
       'BU1TOTAMT', 'GAMT', 'LABORCNT',
       'KOSPI', '환율', 'GDP', '소상공인체감지수', '실업률', '물가지수', '국고채', '금리', '유가등락률',
       '소비자심리지수']] = scaler

In [8]:
data.head()

,CUSTNO,GNO,CBSCORE,CBSCOREGRD,CREDITOTAMT,YSALEAMT,ESTMM,ASSETAMT,IMSAAMT,IMJUAMT,...,KIND_JOB_K,KIND_JOB_L,KIND_JOB_M,KIND_JOB_N,KIND_JOB_O,KIND_JOB_P,KIND_JOB_Q,KIND_JOB_R,KIND_JOB_S,KIND_JOB_T
0,475821,l180202101898,1.483693,-1.008776,-0.182324,5.599410,-0.351065,-0.497246,-0.176818,-0.327516,...,0,0,0,0,0,0,0,0,0,0
1,74417,l230201700120,0.436620,-0.269293,-0.187359,3.004204,-0.774902,-0.434147,-0.395499,0.047573,...,0,0,0,0,0,0,0,0,0,0
2,387787,l110201603233,0.682990,-1.008776,-0.283032,1.765241,1.889216,-0.497246,-0.176818,-0.327516,...,0,0,0,0,0,0,0,0,0,0
3,395418,l230201700254,0.169719,-0.269293,-0.212536,1.647960,-0.744628,-0.497246,-0.176818,-0.327516,...,0,0,0,0,0,0,0,0,0,0
4,190372,l200201601418,-3.033092,2.688638,-0.247784,0.478163,1.616749,-0.202785,-0.351763,-0.327516,...,0,0,0,0,0,0,0,0,0,0

In [10]:
data.to_csv('Standard_Scaler_result.csv',index=False,encoding= "cp949")

 - MinMaxScaler : 0~1값으로 구성되도록한다

In [12]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler = scaler.fit_transform(features)

data[['CBSCORE', 'CBSCOREGRD', 'CREDITOTAMT', 'YSALEAMT',
       'ESTMM', 'ASSETAMT', 'IMSAAMT', 'IMJUAMT', 'BUSAAMT', 'BUJUAMT',
       'BU1TOTAMT', 'GAMT', 'LABORCNT',
       'KOSPI', '환율', 'GDP', '소상공인체감지수', '실업률', '물가지수', '국고채', '금리', '유가등락률',
       '소비자심리지수']] = scaler

data.to_csv('MinMax_Scaler_result.csv',index=False,encoding= "cp949")

In [13]:
data.head()

,CUSTNO,GNO,CBSCORE,CBSCOREGRD,CREDITOTAMT,YSALEAMT,ESTMM,ASSETAMT,IMSAAMT,IMJUAMT,...,KIND_JOB_K,KIND_JOB_L,KIND_JOB_M,KIND_JOB_N,KIND_JOB_O,KIND_JOB_P,KIND_JOB_Q,KIND_JOB_R,KIND_JOB_S,KIND_JOB_T
0,475821,l180202101898,0.949290,0.000000,0.002338,0.223956,0.058085,0.000768,0.004153,0.000000,...,0,0,0,0,0,0,0,0,0,0
1,74417,l230201700120,0.897566,0.166667,0.002221,0.129121,0.014129,0.001920,0.000000,0.015489,...,0,0,0,0,0,0,0,0,0,0
2,387787,l110201603233,0.909736,0.000000,0.000000,0.083846,0.290424,0.000768,0.004153,0.000000,...,0,0,0,0,0,0,0,0,0,0
3,395418,l230201700254,0.884381,0.166667,0.001637,0.079560,0.017268,0.000768,0.004153,0.000000,...,0,0,0,0,0,0,0,0,0,0
4,190372,l200201601418,0.726166,0.833333,0.000818,0.036813,0.262166,0.006143,0.000831,0.000000,...,0,0,0,0,0,0,0,0,0,0

 - RobustScaler
 - MaxAbsScaler : 0을 기준으로 절대값이 가장 큰 수가 1또는 -1이 되도록 변환 -> 해당 기법은 활용하기 어려울 것으로 예상됨

In [14]:
from sklearn.preprocessing import Normalizer 
scaler = Normalizer()
scaler = scaler.fit_transform(features)

data[['CBSCORE', 'CBSCOREGRD', 'CREDITOTAMT', 'YSALEAMT',
       'ESTMM', 'ASSETAMT', 'IMSAAMT', 'IMJUAMT', 'BUSAAMT', 'BUJUAMT',
       'BU1TOTAMT', 'GAMT', 'LABORCNT',
       'KOSPI', '환율', 'GDP', '소상공인체감지수', '실업률', '물가지수', '국고채', '금리', '유가등락률',
       '소비자심리지수']] = scaler

data.to_csv('Normalizer_result.csv',index=False,encoding= "cp949")

In [15]:
data.head()

,CUSTNO,GNO,CBSCORE,CBSCOREGRD,CREDITOTAMT,YSALEAMT,ESTMM,ASSETAMT,IMSAAMT,IMJUAMT,...,KIND_JOB_K,KIND_JOB_L,KIND_JOB_M,KIND_JOB_N,KIND_JOB_O,KIND_JOB_P,KIND_JOB_Q,KIND_JOB_R,KIND_JOB_S,KIND_JOB_T
0,475821,l180202101898,0.000056,5.880046e-08,1.176009e-06,0.000120,2.175617e-06,5.880046e-07,5.880046e-07,0.000000,...,0,0,0,0,0,0,0,0,0,0
1,74417,l230201700120,0.000053,1.176085e-07,1.117281e-06,0.000069,5.292385e-07,1.470107e-06,0.000000e+00,0.000001,...,0,0,0,0,0,0,0,0,0,0
2,387787,l110201603233,0.000053,5.880464e-08,0.000000e+00,0.000045,1.087886e-05,5.880464e-07,5.880464e-07,0.000000,...,0,0,0,0,0,0,0,0,0,0
3,395418,l230201700254,0.000044,9.997635e-08,6.998344e-07,0.000036,5.498699e-07,4.998817e-07,4.998817e-07,0.000000,...,0,0,0,0,0,0,0,0,0,0
4,190372,l200201601418,0.000048,3.998370e-07,4.664765e-07,0.000022,1.112880e-05,5.331160e-06,1.332790e-07,0.000000,...,0,0,0,0,0,0,0,0,0,0

In [22]:
from sklearn.preprocessing import RobustScaler
scaler = RobustScaler()
scaler = scaler.fit_transform(features)

import joblib
scaler_filename = "robust_scaler.save"
joblib.dump(scaler,scaler_filename)

data[['CUSTNO', 'GNO', 'CBSCORE', 'CBSCOREGRD', 'CREDITOTAMT', 'YSALEAMT',
       'ESTMM', 'ASSETAMT', 'IMSAAMT', 'IMJUAMT', 'BUSAAMT', 'BUJUAMT',
       'BU1TOTAMT', 'GAMT', 'BIZNML_x', 'LABORCNT', 'ACTCD', 'KOSPI', '환율',
       'GDP', '소상공인체감지수', '실업률', '물가지수', '국고채', '금리', '유가등락률', '소비자심리지수',
       'KIND_JOB', 'KIND_JOB_A', 'KIND_JOB_B', 'KIND_JOB_C', 'KIND_JOB_D',
       'KIND_JOB_E', 'KIND_JOB_F', 'KIND_JOB_G', 'KIND_JOB_H', 'KIND_JOB_I',
       'KIND_JOB_J', 'KIND_JOB_K', 'KIND_JOB_L', 'KIND_JOB_M', 'KIND_JOB_N',
       'KIND_JOB_O', 'KIND_JOB_P', 'KIND_JOB_Q', 'KIND_JOB_R', 'KIND_JOB_S',
       'KIND_JOB_T']] = scaler

# 데이터 분포 확인

- StandardScaler

In [17]:
data = pd.read_csv("Standard_Scaler_result.csv",encoding="cp949")

In [26]:
df_bu = data[data["ACTCD"]==1]
df_ju = data[data["ACTCD"]==0]

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import seaborn as sns

# 설치된 폰트 출력
font_list = [font.name for font in fm.fontManager.ttflist]
plt.rcParams['font.family'] = 'gulim'
#print(font_list)

In [ ]:
def kdeplot_sub_draw(sub_ax, x, title, size, color, left= 0, right= 0):
    # sns.kdeplot: Fit and plot a univariate or bivariate kernel density estimate
    if left != 0 and right != 0:
        sub_ax.set_xlim(left, right)
    sub_ax.grid(False)
    sub_ax.set_title(title)
    sns.kdeplot(x, ax = sub_ax, shade=True, color=color)
    # median  line draw
    sub_ax.set_xlabel(" ")
    sub_ax.set_ylabel(" ")

In [ ]:
def kdeplot_show(a, b):
    fig, ax = plt.subplots(nrows=5, ncols=5, figsize=(25,20))
    kdeplot_sub_draw(sub_ax=ax[0][0], x=a['CBSCORE'], title='신용점수', size=1, color='xkcd:sky blue',left=-3,right=2)
    ax[0][0].axvline(x=a['CBSCORE'].median(), color='xkcd:sky blue', linestyle='--', linewidth=0.5)
    kdeplot_sub_draw(sub_ax=ax[0][0], x=b['CBSCORE'], title='신용점수', size=1, color='xkcd:salmon',left=-3,right=2)
    ax[0][0].axvline(x=b['CBSCORE'].median(), color='xkcd:salmon', linestyle='--', linewidth=0.5)
    ax[0][0].text(1,0.6,round(a['CBSCORE'].median()-b['CBSCORE'].median(),4),fontsize=15)

    kdeplot_sub_draw(sub_ax=ax[0][1], x=a['CREDITOTAMT'], title='신용차입총액', size=1, color='xkcd:sky blue',left=-5,right=6)
    ax[0][1].axvline(x=a['CREDITOTAMT'].median(), color='xkcd:sky blue', linestyle='--', linewidth=0.5)
    kdeplot_sub_draw(sub_ax=ax[0][1], x=b['CREDITOTAMT'], title='신용차입총액', size=1, color='xkcd:salmon',left=-5,right=6)
    ax[0][1].axvline(x=b['CREDITOTAMT'].median(), color='xkcd:salmon', linestyle='--', linewidth=0.5)
    ax[0][1].text(3.3,0.4,abs(round(a['CREDITOTAMT'].median()-b['CREDITOTAMT'].median(),4)),fontsize=15)


    kdeplot_sub_draw(sub_ax=ax[0][2], x=a['YSALEAMT'], title='연간환산매출액', size=1, color='xkcd:sky blue',left=-2,right=10)
    ax[0][2].axvline(x=a['YSALEAMT'].median(), color='xkcd:sky blue', linestyle='--', linewidth=0.5)
    kdeplot_sub_draw(sub_ax=ax[0][2], x=b['YSALEAMT'], title='연간환산매출액', size=1, color='xkcd:salmon',left=-2,right=10)
    ax[0][2].axvline(x=b['YSALEAMT'].median(), color='xkcd:salmon', linestyle='--', linewidth=0.5)
    ax[0][2].text(8,0.75,abs(round(a['YSALEAMT'].median()-b['YSALEAMT'].median(),4)),fontsize=15)

    kdeplot_sub_draw(sub_ax=ax[0][3], x=a['ESTMM'], title='업력_월', size=1, color='xkcd:sky blue',left=-2,right=6)
    ax[0][3].axvline(x=a['ESTMM'].median(), color='xkcd:sky blue', linestyle='--', linewidth=0.5)
    kdeplot_sub_draw(sub_ax=ax[0][3], x=b['ESTMM'], title='업력_월', size=1, color='xkcd:salmon',left=-2,right=6)
    ax[0][3].axvline(x=b['ESTMM'].median(), color='xkcd:salmon', linestyle='--', linewidth=0.5)
    ax[0][3].text(4.5,1.2,abs(round(a['ESTMM'].median()-b['ESTMM'].median(),4)),fontsize=15)
    
    kdeplot_sub_draw(sub_ax=ax[0][4], x=a['ASSETAMT'], title='자산가액', size=1, color='xkcd:sky blue',left=-5,right=5 )
    ax[0][4].axvline(x=a['ASSETAMT'].median(), color='xkcd:sky blue', linestyle='--', linewidth=0.5)
    kdeplot_sub_draw(sub_ax=ax[0][4], x=b['ASSETAMT'], title='자산가액', size=1, color='xkcd:salmon',left=-5,right=5 )
    ax[0][4].axvline(x=b['ASSETAMT'].median(), color='xkcd:salmon', linestyle='--', linewidth=0.5)
    ax[0][4].text(3,1.1,abs(round(a['ASSETAMT'].median()-b['ASSETAMT'].median(),4)),fontsize=15)
    
    kdeplot_sub_draw(sub_ax=ax[1][0], x=a['IMSAAMT'], title='임차보증금사업장', size=1, color='xkcd:sky blue',left=-3,right=10 )
    ax[1][0].axvline(x=a['IMSAAMT'].median(), color='xkcd:sky blue', linestyle='--', linewidth=0.5)
    kdeplot_sub_draw(sub_ax=ax[1][0], x=b['IMSAAMT'], title='임차보증금사업장', size=1, color='xkcd:salmon',left=-3,right=10 )
    ax[1][0].axvline(x=b['IMSAAMT'].median(), color='xkcd:salmon', linestyle='--', linewidth=0.5)
    ax[1][0].text(8,0.65,abs(round(a['IMSAAMT'].median()-b['IMSAAMT'].median(),4)),fontsize=15)
    
    kdeplot_sub_draw(sub_ax=ax[1][1], x=a['IMJUAMT'], title='임차보증금거주주택', size=1, color='xkcd:sky blue',right=80)
    ax[1][1].axvline(x=a['IMJUAMT'].median(), color='xkcd:sky blue', linestyle='--', linewidth=0.5)
    kdeplot_sub_draw(sub_ax=ax[1][1], x=b['IMJUAMT'], title='임차보증금거주주택', size=1, color='xkcd:salmon',right=80)
    ax[1][1].axvline(x=b['IMJUAMT'].median(), color='xkcd:salmon', linestyle='--', linewidth=0.5)
    ax[1][1].text(1300,0.033,abs(round(a['IMJUAMT'].median()-b['IMJUAMT'].median(),4)),fontsize=15)
    
    kdeplot_sub_draw(sub_ax=ax[1][2], x=a['BUSAAMT'], title='부동산사업장', size=1, color='xkcd:sky blue',left=-100,right=150)
    ax[1][2].axvline(x=a['BUSAAMT'].median(), color='xkcd:sky blue', linestyle='--', linewidth=0.5)
    kdeplot_sub_draw(sub_ax=ax[1][2], x=b['BUSAAMT'], title='부동산사업장', size=1, color='xkcd:salmon',left=-100,right=150)
    ax[1][2].axvline(x=b['BUSAAMT'].median(), color='xkcd:salmon', linestyle='--', linewidth=0.5)
    ax[1][2].text(120,0.016,abs(round(a['BUSAAMT'].median()-b['BUSAAMT'].median(),4)),fontsize=15)
    
    kdeplot_sub_draw(sub_ax=ax[1][3], x=a['BUJUAMT'], title='부동산거주주택', size=1, color='xkcd:sky blue',left=-100,right=400 )
    ax[1][3].axvline(x=a['BUJUAMT'].median(), color='xkcd:sky blue', linestyle='--', linewidth=0.5)
    kdeplot_sub_draw(sub_ax=ax[1][3], x=b['BUJUAMT'], title='부동산거주주택', size=1, color='xkcd:salmon',left=-100,right=400 )
    ax[1][3].axvline(x=b['BUJUAMT'].median(), color='xkcd:salmon', linestyle='--', linewidth=0.5)
    ax[1][3].text(350,0.016,abs(round(a['BUJUAMT'].median()-b['BUJUAMT'].median(),4)),fontsize=15)
    
    kdeplot_sub_draw(sub_ax=ax[1][4], x=a['BU1TOTAMT'], title='부실징후1대출합', size=1, color='xkcd:sky blue',left=-10,right=20 )
    ax[1][4].axvline(x=a['BU1TOTAMT'].median(), color='xkcd:sky blue', linestyle='--', linewidth=0.5)
    kdeplot_sub_draw(sub_ax=ax[1][4], x=b['BU1TOTAMT'], title='부실징후1대출합', size=1, color='xkcd:salmon',left=-10,right =20 )
    ax[1][4].axvline(x=b['BU1TOTAMT'].median(), color='xkcd:salmon', linestyle='--', linewidth=0.5)
    ax[1][4].text(13,0.28,abs(round(a['BU1TOTAMT'].median()-b['BU1TOTAMT'].median(),4)),fontsize=15)
   
    kdeplot_sub_draw(sub_ax=ax[2][0], x=a['GAMT'], title='보증금액', size=1, color='xkcd:sky blue',left=-2,right=4 )
    ax[2][0].axvline(x=a['GAMT'].median(), color='xkcd:sky blue', linestyle='--', linewidth=0.5)
    kdeplot_sub_draw(sub_ax=ax[2][0], x=b['GAMT'], title='보증금액', size=1, color='xkcd:salmon',left=-2,right=4 )
    ax[2][0].axvline(x=b['GAMT'].median(), color='xkcd:salmon', linestyle='--', linewidth=0.5)
    ax[2][0].text(3,0.7,abs(round(a['GAMT'].median()-b['GAMT'].median(),4)),fontsize=15)
    
    kdeplot_sub_draw(sub_ax=ax[2][1], x=a['LABORCNT'], title='종업원수', size=1, color='xkcd:sky blue',left=-1,right=4 )
    ax[2][1].axvline(x=a['LABORCNT'].median(), color='xkcd:sky blue', linestyle='--', linewidth=0.5)
    kdeplot_sub_draw(sub_ax=ax[2][1], x=b['LABORCNT'], title='종업원수', size=1, color='xkcd:salmon',left=-1,right=4 )
    ax[2][1].axvline(x=b['LABORCNT'].median(), color='xkcd:salmon', linestyle='--', linewidth=0.5)
    ax[2][1].text(3.51,1.4,abs(round(a['LABORCNT'].median()-b['LABORCNT'].median(),4)),fontsize=15)
       
    kdeplot_sub_draw(sub_ax=ax[2][2], x=a['KOSPI'], title='KOSPI', size=1, color='xkcd:sky blue',left=-2,right=4 )
    ax[2][2].axvline(x=a['KOSPI'].median(), color='xkcd:sky blue', linestyle='--', linewidth=0.5)
    kdeplot_sub_draw(sub_ax=ax[2][2], x=b['KOSPI'], title='KOSPI', size=1, color='xkcd:salmon',left=-2,right=4 )
    ax[2][2].axvline(x=b['KOSPI'].median(), color='xkcd:salmon', linestyle='--', linewidth=0.5)
    ax[2][2].text(2.5,0.9,abs(round(a['KOSPI'].median()-b['KOSPI'].median(),4)),fontsize=15)
    
    kdeplot_sub_draw(sub_ax=ax[2][3], x=a['환율'], title='환율', size=1, color='xkcd:sky blue',left=-2,right=3 )
    ax[2][3].axvline(x=a['환율'].median(), color='xkcd:sky blue', linestyle='--', linewidth=0.5)
    kdeplot_sub_draw(sub_ax=ax[2][3], x=b['환율'], title='환율', size=1, color='xkcd:salmon' ,left=-2,right=3)
    ax[2][3].axvline(x=b['환율'].median(), color='xkcd:salmon', linestyle='--', linewidth=0.5)
    ax[2][3].text(2,0.75,abs(round(a['환율'].median()-b['환율'].median(),4)),fontsize=15)
    
    kdeplot_sub_draw(sub_ax=ax[2][4], x=a['GDP'], title='GDP', size=1, color='xkcd:sky blue' ,left=-3,right=3)
    ax[2][4].axvline(x=a['GDP'].median(), color='xkcd:sky blue', linestyle='--', linewidth=0.5)
    kdeplot_sub_draw(sub_ax=ax[2][4], x=b['GDP'], title='GDP', size=1, color='xkcd:salmon' ,left=-3,right=3)
    ax[2][4].axvline(x=b['GDP'].median(), color='xkcd:salmon', linestyle='--', linewidth=0.5)
    ax[2][4].text(2,0.65,abs(round(a['GDP'].median()-b['GDP'].median(),4)),fontsize=15)
    
    kdeplot_sub_draw(sub_ax=ax[3][0], x=a['소상공인체감지수'], title='소상공인BSI', size=1, color='xkcd:sky blue' ,left=-3,right=3)
    ax[3][0].axvline(x=a['소상공인체감지수'].median(), color='xkcd:sky blue', linestyle='--', linewidth=0.5)
    kdeplot_sub_draw(sub_ax=ax[3][0], x=b['소상공인체감지수'], title='소상공인BSI', size=1, color='xkcd:salmon' ,left=-3,right=3)
    ax[3][0].axvline(x=b['소상공인체감지수'].median(), color='xkcd:salmon', linestyle='--', linewidth=0.5)
    ax[3][0].text(1.5,0.76,abs(round(a['소상공인체감지수'].median()-b['소상공인체감지수'].median(),4)),fontsize=15)
    
    kdeplot_sub_draw(sub_ax=ax[3][1], x=a['실업률'], title='실업률', size=1, color='xkcd:sky blue',left=-3,right=3 )
    ax[3][1].axvline(x=a['실업률'].median(), color='xkcd:sky blue', linestyle='--', linewidth=0.5)
    kdeplot_sub_draw(sub_ax=ax[3][1], x=b['실업률'], title='실업률', size=1, color='xkcd:salmon' ,left=-3,right=3)
    ax[3][1].axvline(x=b['실업률'].median(), color='xkcd:salmon', linestyle='--', linewidth=0.5)
    ax[3][1].text(2.5,0.93,abs(round(a['실업률'].median()-b['실업률'].median(),4)),fontsize=15)
  
    kdeplot_sub_draw(sub_ax=ax[3][2], x=a['물가지수'], title='물가지수', size=1, color='xkcd:sky blue' ,left=-3,right=3)
    ax[3][2].axvline(x=a['물가지수'].median(), color='xkcd:sky blue', linestyle='--', linewidth=0.5)
    kdeplot_sub_draw(sub_ax=ax[3][2], x=b['물가지수'], title='물가지수', size=1, color='xkcd:salmon',left=-3,right=3 )
    ax[3][2].axvline(x=b['물가지수'].median(), color='xkcd:salmon', linestyle='--', linewidth=0.5)
    ax[3][2].text(1.9,0.75,abs(round(a['물가지수'].median()-b['물가지수'].median(),4)),fontsize=15)
    
    kdeplot_sub_draw(sub_ax=ax[3][3], x=a['국고채'], title='국고채수익률', size=1, color='xkcd:sky blue' ,left=-3,right=3)
    ax[3][3].axvline(x=a['국고채'].median(), color='xkcd:sky blue', linestyle='--', linewidth=0.5)
    kdeplot_sub_draw(sub_ax=ax[3][3], x=b['국고채'], title='국고채수익률', size=1, color='xkcd:salmon' ,left=-3,right=3)
    ax[3][3].axvline(x=b['국고채'].median(), color='xkcd:salmon', linestyle='--', linewidth=0.5)
    ax[3][3].text(2.5,0.75,abs(round(a['국고채'].median()-b['국고채'].median(),4)),fontsize=15)
    
    kdeplot_sub_draw(sub_ax=ax[3][4], x=a['금리'], title='금리', size=1, color='xkcd:sky blue' ,left=-5,right=3)
    ax[3][4].axvline(x=a['금리'].median(), color='xkcd:sky blue', linestyle='--', linewidth=0.5)
    kdeplot_sub_draw(sub_ax=ax[3][4], x=b['금리'], title='금리', size=1, color='xkcd:salmon' ,left=-5,right=3)
    ax[3][4].axvline(x=b['금리'].median(), color='xkcd:salmon', linestyle='--', linewidth=0.5)
    ax[3][4].text(2,1.3,abs(round(a['금리'].median()-b['금리'].median(),4)),fontsize=15)
    
    kdeplot_sub_draw(sub_ax=ax[4][0], x=a['유가등락률'], title='WTI현물유가등락률', size=1, color='xkcd:sky blue' ,left=-3,right=3)
    ax[4][0].axvline(x=a['유가등락률'].median(), color='xkcd:sky blue', linestyle='--', linewidth=0.5)
    kdeplot_sub_draw(sub_ax=ax[4][0], x=b['유가등락률'], title='WTI현물유가등락률', size=1, color='xkcd:salmon' ,left=-3,right=3)
    ax[4][0].axvline(x=b['유가등락률'].median(), color='xkcd:salmon', linestyle='--', linewidth=0.5)
    ax[4][0].text(2,0.7,abs(round(a['유가등락률'].median()-b['유가등락률'].median(),4)),fontsize=15)
    
    kdeplot_sub_draw(sub_ax=ax[4][1], x=a['소비자심리지수'], title='소비자심리지수', size=1, color='xkcd:sky blue' ,left=-3,right=2)
    ax[4][1].axvline(x=a['소비자심리지수'].median(), color='xkcd:sky blue', linestyle='--', linewidth=0.5)
    kdeplot_sub_draw(sub_ax=ax[4][1], x=b['소비자심리지수'], title='소비자심리지수', size=1, color='xkcd:salmon' ,left=-3,right=2)
    ax[4][1].axvline(x=b['소비자심리지수'].median(), color='xkcd:salmon', linestyle='--', linewidth=0.5)
    ax[4][1].text(1.5,0.9,abs(round(a['소비자심리지수'].median()-b['소비자심리지수'].median(),4)),fontsize=15)
    
    kdeplot_sub_draw(sub_ax=ax[4][2], x=a['ONEHOT'], title='업종', size=1, color='xkcd:sky blue',left=0,right=20)
    ax[4][2].axvline(x=a['ONEHOT'].median(), color='xkcd:sky blue', linestyle='--', linewidth=0.5)
    kdeplot_sub_draw(sub_ax=ax[4][2], x=b['ONEHOT'], title='업종', size=1, color='xkcd:salmon',left=0,right=20)
    ax[4][2].axvline(x=b['ONEHOT'].median(), color='xkcd:salmon', linestyle='--', linewidth=0.5)
    ax[4][2].text(20,0.20,abs(round(a['ONEHOT'].median()-b['ONEHOT'].median(),4)),fontsize=15)
    
    


kdeplot_show(df_ju, df_bu)

In [ ]:
def ori_kdeplot_show(a, b):
    fig, ax = plt.subplots(nrows=5, ncols=5, figsize=(25,20))
    kdeplot_sub_draw(sub_ax=ax[0][0], x=a['CBSCORE'], title='신용점수', size=1, color='xkcd:sky blue')
    kdeplot_sub_draw(sub_ax=ax[0][0], x=b['CBSCORE'], title='신용점수', size=1, color='xkcd:salmon')

    kdeplot_sub_draw(sub_ax=ax[0][1], x=a['CREDITOTAMT'], title='신용차입총액', size=1, color='xkcd:sky blue')
    kdeplot_sub_draw(sub_ax=ax[0][1], x=b['CREDITOTAMT'], title='신용차입총액', size=1, color='xkcd:salmon')


    kdeplot_sub_draw(sub_ax=ax[0][2], x=a['YSALEAMT'], title='연간환산매출액', size=1, color='xkcd:sky blue')
    kdeplot_sub_draw(sub_ax=ax[0][2], x=b['YSALEAMT'], title='연간환산매출액', size=1, color='xkcd:salmon')

    kdeplot_sub_draw(sub_ax=ax[0][3], x=a['ESTMM'], title='업력_월', size=1, color='xkcd:sky blue')
    kdeplot_sub_draw(sub_ax=ax[0][3], x=b['ESTMM'], title='업력_월', size=1, color='xkcd:salmon')
    
    kdeplot_sub_draw(sub_ax=ax[0][4], x=a['ASSETAMT'], title='자산가액', size=1, color='xkcd:sky blue')
    kdeplot_sub_draw(sub_ax=ax[0][4], x=b['ASSETAMT'], title='자산가액', size=1, color='xkcd:salmon')
    
    kdeplot_sub_draw(sub_ax=ax[1][0], x=a['IMSAAMT'], title='임차보증금사업장', size=1, color='xkcd:sky blue')
    kdeplot_sub_draw(sub_ax=ax[1][0], x=b['IMSAAMT'], title='임차보증금사업장', size=1, color='xkcd:salmon' )
    
    kdeplot_sub_draw(sub_ax=ax[1][1], x=a['IMJUAMT'], title='임차보증금거주주택', size=1, color='xkcd:sky blue')
    kdeplot_sub_draw(sub_ax=ax[1][1], x=b['IMJUAMT'], title='임차보증금거주주택', size=1, color='xkcd:salmon')
    
    kdeplot_sub_draw(sub_ax=ax[1][2], x=a['BUSAAMT'], title='부동산사업장', size=1, color='xkcd:sky blue')
    kdeplot_sub_draw(sub_ax=ax[1][2], x=b['BUSAAMT'], title='부동산사업장', size=1, color='xkcd:salmon')
    
    kdeplot_sub_draw(sub_ax=ax[1][3], x=a['BUJUAMT'], title='부동산거주주택', size=1, color='xkcd:sky blue' )
    kdeplot_sub_draw(sub_ax=ax[1][3], x=b['BUJUAMT'], title='부동산거주주택', size=1, color='xkcd:salmon')
    
    kdeplot_sub_draw(sub_ax=ax[1][4], x=a['BU1TOTAMT'], title='부실징후1대출합', size=1, color='xkcd:sky blue')
    kdeplot_sub_draw(sub_ax=ax[1][4], x=b['BU1TOTAMT'], title='부실징후1대출합', size=1, color='xkcd:salmon')
   
    kdeplot_sub_draw(sub_ax=ax[2][0], x=a['GAMT'], title='보증금액', size=1, color='xkcd:sky blue')
    kdeplot_sub_draw(sub_ax=ax[2][0], x=b['GAMT'], title='보증금액', size=1, color='xkcd:salmon')
    
    kdeplot_sub_draw(sub_ax=ax[2][1], x=a['LABORCNT'], title='종업원수', size=1, color='xkcd:sky blue' )
    kdeplot_sub_draw(sub_ax=ax[2][1], x=b['LABORCNT'], title='종업원수', size=1, color='xkcd:salmon')
       
    kdeplot_sub_draw(sub_ax=ax[2][2], x=a['KOSPI'], title='KOSPI', size=1, color='xkcd:sky blue' )
    kdeplot_sub_draw(sub_ax=ax[2][2], x=b['KOSPI'], title='KOSPI', size=1, color='xkcd:salmon')
    
    kdeplot_sub_draw(sub_ax=ax[2][3], x=a['환율'], title='환율', size=1, color='xkcd:sky blue')
    kdeplot_sub_draw(sub_ax=ax[2][3], x=b['환율'], title='환율', size=1, color='xkcd:salmon' )
    
    kdeplot_sub_draw(sub_ax=ax[2][4], x=a['GDP'], title='GDP', size=1, color='xkcd:sky blue')
    kdeplot_sub_draw(sub_ax=ax[2][4], x=b['GDP'], title='GDP', size=1, color='xkcd:salmon')
    
    kdeplot_sub_draw(sub_ax=ax[3][0], x=a['소상공인체감지수'], title='소상공인BSI', size=1, color='xkcd:sky blue')
    kdeplot_sub_draw(sub_ax=ax[3][0], x=b['소상공인체감지수'], title='소상공인BSI', size=1, color='xkcd:salmon' )
    
    kdeplot_sub_draw(sub_ax=ax[3][1], x=a['실업률'], title='실업률', size=1, color='xkcd:sky blue' )
    kdeplot_sub_draw(sub_ax=ax[3][1], x=b['실업률'], title='실업률', size=1, color='xkcd:salmon')
  
    kdeplot_sub_draw(sub_ax=ax[3][2], x=a['물가지수'], title='물가지수', size=1, color='xkcd:sky blue')
    kdeplot_sub_draw(sub_ax=ax[3][2], x=b['물가지수'], title='물가지수', size=1, color='xkcd:salmon' )
    
    kdeplot_sub_draw(sub_ax=ax[3][3], x=a['국고채'], title='국고채수익률', size=1, color='xkcd:sky blue')
    kdeplot_sub_draw(sub_ax=ax[3][3], x=b['국고채'], title='국고채수익률', size=1, color='xkcd:salmon')
    
    kdeplot_sub_draw(sub_ax=ax[3][4], x=a['금리'], title='금리', size=1, color='xkcd:sky blue')
    kdeplot_sub_draw(sub_ax=ax[3][4], x=b['금리'], title='금리', size=1, color='xkcd:salmon')
    
    kdeplot_sub_draw(sub_ax=ax[4][0], x=a['유가등락률'], title='WTI현물유가등락률', size=1, color='xkcd:sky blue')
    kdeplot_sub_draw(sub_ax=ax[4][0], x=b['유가등락률'], title='WTI현물유가등락률', size=1, color='xkcd:salmon' )
    
    kdeplot_sub_draw(sub_ax=ax[4][1], x=a['소비자심리지수'], title='소비자심리지수', size=1, color='xkcd:sky blue' )
    kdeplot_sub_draw(sub_ax=ax[4][1], x=b['소비자심리지수'], title='소비자심리지수', size=1, color='xkcd:salmon' )
    
    kdeplot_sub_draw(sub_ax=ax[4][2], x=a['ONEHOT'], title='업종', size=1, color='xkcd:sky blue')
    kdeplot_sub_draw(sub_ax=ax[4][2], x=b['ONEHOT'], title='업종', size=1, color='xkcd:salmon')

ori_kdeplot_show(data, df_bu)

- MinMaxScaler

- RobustScaler